name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1.3
      with:
        default: true
        ldproxy: true
    - uses: Swatinem/rust-cache@v1
    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: check
        args: --examples --verbose
    - name: Fmt check
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: -- --check
    - name: Clippy check
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: --all-features -- -D warnings