name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install Rust for Xtensa
      uses: esp-rs/xtensa-toolchain@v1.3
      with:
        default: true
        ldproxy: true
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo check --examples --all-features
    - name: Fmt check
      run: cargo fmt --check
    - name: Clippy check
      run: cargo clippy --all-features -- -D warnings